### ISSUE TITLE
Safe HTML in data

### ISSUE THREAD

**Issue by rbiggs** [developit/vhtml#11]
Is there any way to render safe html in data, kind of like dangerouslySetInnerHTML in React? I'm talking about having some data like:
```
{
  firstName: 'John',
  lastName: '<b>Doe</b>'
}
```

**Comment by developit** [comment]
This can now be done using a Fragment with dangerouslySetInnerHTML:

```js
const raw = html => vhtml(null, {
  dangerouslySetInnerHTML: { __html: html }
});

render(html`
  <div>
    ${raw(`<span>raw html here</span>`)}
  </div>
`)
```
