### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by ithinkihaveacat** [developit/vhtml#22]
Is it possible to publish a new version?

A few enhancements have been merged recently, but they're difficult to use via npm.

**Comment by bjacobel** [comment]
I was also interested in a new version - if anyone else comes here looking for the same, I just published a "v2.2.0" to https://www.npmjs.com/package/@bjacobel/vhtml that represents the state of master as of 8a0ae24ae616758db5034a40a33fff1c0a924fe6.

**Comment by developit** [comment]
Sorry for dropping the ball on this!

**Comment by developit** [comment]
Released 2.2.0! https://github.com/developit/vhtml/releases/tag/2.2.0
